name: Build Mauricio FC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-dev gcc-arm-none-eabi g++ make

   - name: Init submodules
        run: |
          git submodule update --init --recursive

      - name: Build bootloader
        run: |
          ./Tools/scripts/build_bootloaders.py MambaF405v2_Mauricio

      - name: Configure
        run: |
          ./waf configure --board MambaF405v2_Mauricio

      - name: Build
        run: |
          ./waf copter

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/MambaF405v2_Mauricio/bin/arducopter.apj
